# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-frontend:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ~14
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: zip artifact
        run: |
          mkdir _build
          cp deploy.ps1 .deployment _build
          zip release.zip server.js web.config CreateDeployContentPackage.ps1 -r
          cp CreateDeployContentPackage.ps1 _build
          cp release.zip _build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: |
            _build

      - uses: zwaldowski/semver-release-action@v1
        with:
          bump: minor
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy-front-end:
    name: Deploy frontend
    runs-on: ubuntu-latest
    needs: [build-frontend]

    steps:
      - name: Download FE artifact
        uses: actions/download-artifact@v2
        with:
          name: node-app
          path: nextjs

      #- run: unzip release.zip -d release

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy FE to ui app service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "vc-nextapp"
          package: nextjs

      - name: Azure logout
        run: |
          az logout
        if: always()
